apps/curriculum/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'curriculum'

urlpatterns = [
    path('curriculum-maintenance-and-management/', views.curriculum_maintenance_and_management, name='curriculum_maintenance_and_management'),
    path('curriculum-maintenance-and-management/update/', views.edit_institute, name='edit_institute'),
    path('<slug:institute_slug>/<slug:program_slug>/view/', views.view_program_detail, name='view_program_detail'),
    path('<slug:institute_slug>/<slug:program_slug>/update/', views.update_program_detail, name='update_program_detail'),
    path('<slug:institute_slug>/<slug:program_slug>/add/', views.add_program_detail, name='add_program_detail'),

    # Program Chairperson
    path('<slug:program_slug>/', views.curriculum, name='curriculum'),
    path('<slug:institute_slug>/<slug:program_slug>/view/', views.view_program_detail, name='view_program_detail'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/dashboard/urls.py
from django.urls import path
from .import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('faculty-workload/<str:username>/', views.faculty_workload, name='faculty-workload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from apps.user.views import signup, verify_account
from config.views import CourseListAPIView, NotificationListView, ProtectedMediaView,  SchedulerDataAPIView, UserCoursesView, check_unique, home_redirect
from django.contrib.auth.decorators import login_required

admin.site.site_title = 'administrator'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', signup, name='signup'),
    path('accounts/verify-account/', verify_account, name='verify-account'),
    path('accounts/', include('allauth.urls')),
    path('', home_redirect, name="home_redirect"),
    path('__reload__/', include('django_browser_reload.urls')), #remove this during production
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    path('timetable/', include('apps.timetable.urls', namespace='schedules')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('institute/', include('apps.institutes.urls', namespace='institutes')),
    path('program/', include('apps.programs.urls', namespace="programs")),
    path('faculty-and-staff/', include('apps.faculty.urls', namespace="faculty")),
    path("__debug__/", include("debug_toolbar.urls")), #remove this during production
    path('check-unique/', check_unique, name='check_unique'),

    #Django Rest Framework
    path('api/courses/', CourseListAPIView.as_view(), name='course_list_api'),
    path('api/courses/<int:member_id>', UserCoursesView.as_view(), name='instructor_assigned_courses'),
    path('api/prepare-ga-data/<int:user_group_id>/', SchedulerDataAPIView.as_view(), name='prepare-ga-data'),
    path('api/notifications/', NotificationListView.as_view(), name='notification-list'),

    #Protected Media
    path('media/<path:path>', login_required(ProtectedMediaView.as_view()), name='protected_media'),
]   
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/dashboard/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from apps.curriculum.models import CurriculumYear, Programs
from apps.dashboard.common.greeting_message_services import GreetingMessage
from apps.institutes.models import Institutes
from apps.timetable.common.item_per_page_utils import validate_items_per_page
from apps.user.models import User
from apps.user.utils import get_template_by_user_type
from apps.user.common.group_members_utils import get_faculty_and_staff_info

@login_required
def dashboard(request):
    template = get_template_by_user_type(request.user, 'dashboard')
    
    # Greeting Message
    greeting_service = GreetingMessage()
    greeting_message = greeting_service.get_greeting_message()

    if template and request.user.user_type in [4]:
        institute = get_object_or_404(Institutes, user=request.user)
        program = get_object_or_404(Programs, user=request.user)
        curriculum_with_courses = CurriculumYear.objects.filter(
          courses__program=program
        ).order_by('-curriculum_id').first()
        
        if curriculum_with_courses:
          request.session['curriculum_id'] = curriculum_with_courses.curriculum_id
          program.curriculum_id = curriculum_with_courses.curriculum_id
        else:
          # No curriculum found, set a flag or handle accordingly
          program.curriculum_id = None  # Or set to a default value if needed
      
        user_info = get_faculty_and_staff_info(request)

        items_per_page = request.GET.get('items_per_page', 25)
        page_number = request.GET.get('page', 1)
        group_id = request.GET.get('group', None)

        # Validate items per page
        validated_items_per_page = validate_items_per_page(items_per_page, request, page_number, group_id)
        if isinstance(validated_items_per_page, HttpResponseRedirect):
            return validated_items_per_page
        # Update items per page
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            # If AJAX request, return only the partial template
            return HttpResponse(render(request, 'partials/_faculty_staff_list.html', {
                'faculty_and_staff': user_info['faculty_and_staff'],
            }).content)
        
        # If standard request, return the full dashboard template
        return render(request, template, {
            **user_info,
            'greeting_message': greeting_message,
            'institute': institute,
        })
    
    elif template and request.user.user_type in [1, 2, 3]:
        return render(request, template)
    
    else:
        raise Http404("Template not found")

@login_required
def faculty_workload(request, username):
    template = get_template_by_user_type(request.user, 'faculty-workload')
    user = get_object_or_404(User, username=username)
    if template and request.user.user_type in [3, 4]:
            faculty_and_staff = User.objects.filter(institute=request.user.institute,program=request.user.program)
            program_name = request.user.program.program_name
            program_code = request.user.program.program_code
            institute_name = request.user.institute.institute_name
            return render(request, template, {
                'faculty_and_staff': faculty_and_staff,
                'program_name': program_name,
                'institute_name': institute_name,
                'program_code': program_code,
                'user': user,
            })
    raise Http404("Template not found")

templates/pages/registrar/curriculum-maintenance-and-management.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
  Programs
{% endblock title %}
{% block content %}
  {% include "./includes/_navbar.html" %}
  {% include "./includes/_add_program_modal.html" %}
  {% include "./includes/_add_institute_modal.html" %}
  <div class="w-full lg:ps-64 bg-gray-100 h-full">
    <div class="p-6 space-y-3">
      <p class="text-2xl font-extrabold text-gray-900 uppercase">Curriculum Maintenance and Management</p>
      <div class="hs-accordion-group ">
        <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center bg-white border first:rounded-t-lg last:rounded-b-lg">
          <div class="sm:col-span-1">
            <label for="hs-as-table-product-review-search" class="sr-only">Search</label>
            <div class="relative">
              <input type="text"
                     id="hs-as-table-product-review-search"
                     name="hs-as-table-product-review-search"
                     class="py-2 px-3 ps-11 block w-full border-gray-200 rounded-lg text-sm focus:border-primary-500 focus:ring-primary-500 disabled:opacity-50 disabled:pointer-events-none"
                     placeholder="Search">
              <div class="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-4">
                <svg class="size-4 text-gray-400"
                     xmlns="http://www.w3.org/2000/svg"
                     width="16"
                     height="16"
                     fill="currentColor"
                     viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                </svg>
              </div>
            </div>
          </div>
          <div class="sm:col-span-2">
            <div class="inline-flex gap-x-2">
              <a type="button"
                 href="{% url 'curriculum:edit_institute' %}"
                 class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-50 disabled:pointer-events-none">
                Edit Institute
              </a>
              <button data-hs-overlay="#add-institute"
                      aria-haspopup="dialog"
                      aria-expanded="false"
                      aria-controls="hs-scale-animation-modal"
                      type="button"
                      class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-50 disabled:pointer-events-none">
                Add Institute
              </button>
              <button data-hs-overlay="#add-program"
                      aria-haspopup="dialog"
                      aria-expanded="false"
                      aria-controls="hs-scale-animation-modal"
                      type="button"
                      class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-50 disabled:pointer-events-none">
                Add Program
              </button>
            </div>
          </div>
        </div>
        {% if institutes %}
          {% for institute in institutes %}
            <div class="hs-accordion bg-white border -mt-px first:rounded-t-lg last:rounded-b-lg"
                 id="hs-bordered-heading-one">
              <!-- Display Institute and Programs-->
              <button class="hs-accordion-toggle uppercase hs-accordion-active:text-primary-600 inline-flex items-center gap-x-3 w-full font-semibold text-start text-gray-800 py-4 px-5 hover:text-gray-500 disabled:opacity-50 disabled:pointer-events-none">
                <svg class="hs-accordion-active:hidden block size-3.5"
                     xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor"
                     stroke-width="2"
                     stroke-linecap="round"
                     stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5v14"></path>
                </svg>
                <svg class="hs-accordion-active:block hidden size-3.5"
                     xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor"
                     stroke-width="2"
                     stroke-linecap="round"
                     stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                </svg>
                {{ institute.institute_name }} ({{ institute.acronym }})
              </button>
              <div class="hs-accordion-content hidden w-full overflow-hidden transition-[height] duration-300">
                <div class="pb-4 px-5">
                  <div class="flex flex-col">
                    <div class="p-1.5 min-w-full inline-block align-middle">
                      <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
                        <table class="min-w-full divide-y divide-gray-200">
                          <tbody class="divide-y divide-gray-200">
                            {% if institute.programs_set.all %}
                              {% for program in institute.programs_set.all %}
                                <tr class="bg-white hover:bg-gray-50">
                                  <td class="size-px whitespace-nowrap">
                                    <div class="px-6 py-3">
                                      {% if program.curriculum_id %}
                                        <a href="{% url 'curriculum:view_program_detail' institute_slug=institute.institute_slug program_slug=program.program_slug %}?curriculum={{ program.curriculum_id }}">
                                          <span class="text-sm text-gray-600">{{ program.program_name }} ({{ program.program_code }})</span> </a>
                                      {% else %}
                                        <a href="{% url 'curriculum:add_program_detail' institute_slug=institute.institute_slug program_slug=program.program_slug %}"> <span class="text-sm text-gray-600">{{ program.program_name }} ({{ program.program_code }})</span> </a>
                                      {% endif %}
                                    </div>
                                  </td>
                                  <td class="size-px whitespace-nowrap text-end">
                                    <div class="px-6 py-3">
                                      {% if program.curriculum_id %}
                                        <a href="{% url 'curriculum:view_program_detail' institute_slug=institute.institute_slug program_slug=program.program_slug %}?curriculum={{ program.curriculum_id }}"
                                           type="button"
                                           class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none">
                                          View
                                        </a>
                                      {% else %}
                                        <a href="{% url 'curriculum:add_program_detail' institute_slug=institute.institute_slug program_slug=program.program_slug %}"
                                           type="button"
                                           class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-50 disabled:pointer-events-none">
                                          Add Courses
                                        </a>
                                      {% endif %}
                                    </div>
                                  </td>
                                </tr>
                              {% endfor %}
                            {% else %}
                              <tr class="bg-white hover:bg-gray-50">
                                <td class="size-px whitespace-nowrap">
                                  <div class="px-6 py-3">{% include "partials/_no_data.html" %}</div>
                                </td>
                              </tr>
                            {% endif %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="min-h-60 flex flex-col bg-white border shadow-sm rounded-b-xl">{% include "partials/_no_data.html" %}</div>
        {% endif %}
        <!-- End of Display Institute and Programs-->
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/registrar/dashboard.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
  Dashboard
{% endblock title %}
{% block content %}
  {% include "./includes/_navbar.html" %}
  <div class="w-full lg:ps-64 bg-gray-100 h-full">
    <div class="p-6 space-y-3">
      <p class="text-2xl font-extrabold text-gray-900">Welcome back, {{ request.user.first_name }}!</p>
      <div class="px-6 py-4 bg-white border rounded-lg"></div>
    </div>
  </div>
{% endblock content %}

templates/pages/registrar/update-institute.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
  Curriculum Maintenance and Management
{% endblock title %}
{% block content %}
  {% include "./includes/_navbar.html" %}
  {% include "./includes/_add_program_modal.html" %}
  <div class="w-full lg:ps-64 bg-gray-100 h-full">
    <div class="p-6 space-y-3">
      <p class="text-2xl font-extrabold text-gray-900 uppercase">Curriculum Maintenance and Management</p>
      <div class="px-6 py-4 border-gray-200 bg-white border rounded-lg">
        <div class="flex justify-end gap-2">
          <a type="button"
             href="{% url 'curriculum:curriculum_maintenance_and_management' %}"
             class="py-2 px-3 iinline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none">
            Cancel
          </a>
          <button form="updateInstituteForm"
                  type="submit"
                  name="UpdateInstituteSubmit"
                  class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-50 disabled:pointer-events-none">
            Save Changes
          </button>
        </div>
      </div>
      <div class="border rounded-lg overflow-hidden">
        <div class="px-6 py-4 border-b border-gray-200 bg-primary-600">
          <p class="text-2xl font-extrabold text-white uppercase">{{ year_level }}</p>
          <p class="text-sm text-white">{{ semester }}</p>
        </div>
        <form method="post" id="updateInstituteForm">
          {% csrf_token %}
          {% if institutes %}
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50 rounded-lg">
                <tr>
                  <th scope="col" class="px-6 py-3 text-start">
                    <p class="group inline-flex items-center gap-x-2 text-xs font-semibold uppercase text-gray-800">#</p>
                  </th>
                  <th scope="col" class="px-6 py-3 text-start">
                    <p class="group inline-flex items-center gap-x-2 text-xs font-semibold uppercase text-gray-800">Institute Code</p>
                  </th>
                  <th scope="col" class="px-6 py-3 text-start">
                    <p class="group inline-flex items-center gap-x-2 text-xs font-semibold uppercase text-gray-800">Institute Name</p>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for institute in institutes %}
                  <tr class="bg-white">
                    <td>
                      <p class="row-number px-6 text-sm text-gray-800">{{ forloop.counter }}</p>
                      <input type="hidden"
                             name="institute_id_{{ institute.institute_id }}"
                             value="{{ institute.institute_id }}">
                    </td>
                    <td>
                      <input type="text"
                             value="{{ institute.acronym }}"
                             name="acronym_{{ institute.institute_id }}"
                             autocomplete="off"
                             maxlength="10"
                             required
                             class="py-2 px-3 block w-full border-gray-200 rounded-lg text-sm focus:border-primary-500 focus:ring-primary-500 disabled:opacity-50 disabled:pointer-events-none"
                             placeholder="Institute Code">
                    </td>
                    <td>
                      <input type="text"
                             value="{{ institute.institute_name }}"
                             name="institute_name_{{ institute.institute_id }}"
                             autocomplete="off"
                             maxlength="100"
                             required
                             class="no-spinner py-2 px-3 block w-full border-gray-200 rounded-lg text-sm focus:border-primary-500 focus:ring-primary-500 disabled:opacity-50 disabled:pointer-events-none"
                             placeholder="Institute Name">
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div class="min-h-60 flex flex-col bg-white border shadow-sm rounded-b-xl">{% include "partials/_no_data.html" %}</div>
          {% endif %}
        </form>
        <!-- End of Display Institute and Programs-->
      </div>
    </div>
  </div>
{% endblock content %}