apps/dashboard/urls.py
from django.urls import path
from .import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('faculty-workload/<str:username>/', views.faculty_workload, name='faculty-workload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/faculty/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'faculty'

urlpatterns = [
    path('', views.faculty, name='faculty'),  
    path('faculty-workload/', views.faculty_workload, name='faculty-workload'),  
    path('assign-faculty/', views.assign_faculty, name='assign-faculty'),  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/programs/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'programs'

urlpatterns = [
     path('', views.programs, name='programs'),
     path('curriculum-version/', views.curriculum_version, name='curriculum-version'),
     path('curriculum-version/courses/', views.courses, name='courses'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/user/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'user'

urlpatterns = [
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('notification/<str:username>/', views.notification, name='notification'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from apps.user.views import signup, verify_account
from config.views import CourseListAPIView, NotificationListView, ProtectedMediaView,  SchedulerDataAPIView, UserCoursesView, check_unique, home_redirect
from django.contrib.auth.decorators import login_required

admin.site.site_title = 'administrator'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', signup, name='signup'),
    path('accounts/verify-account/', verify_account, name='verify-account'),
    path('accounts/', include('allauth.urls')),
    path('', home_redirect, name="home_redirect"),
    path('__reload__/', include('django_browser_reload.urls')), #remove this during production
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    path('timetable/', include('apps.timetable.urls', namespace='schedules')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('institute/', include('apps.institutes.urls', namespace='institutes')),
    path('program/', include('apps.programs.urls', namespace="programs")),
    path('faculty-and-staff/', include('apps.faculty.urls', namespace="faculty")),
    path("__debug__/", include("debug_toolbar.urls")), #remove this during production
    path('check-unique/', check_unique, name='check_unique'),

    #Django Rest Framework
    path('api/courses/', CourseListAPIView.as_view(), name='course_list_api'),
    path('api/courses/<int:member_id>', UserCoursesView.as_view(), name='instructor_assigned_courses'),
    path('api/prepare-ga-data/<int:user_group_id>/', SchedulerDataAPIView.as_view(), name='prepare-ga-data'),
    path('api/notifications/', NotificationListView.as_view(), name='notification-list'),

    #Protected Media
    path('media/<path:path>', login_required(ProtectedMediaView.as_view()), name='protected_media'),
]   
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/dean/includes/breadcrumb.html
<ol class="flex items-center whitespace-nowrap">
    <li class="inline-flex items-center">
        <a class="flex items-center text-sm text-gray-500 hover:text-primary-600 focus:outline-none focus:text-primary-600"
           href="#">
            <svg class="flex-shrink-0 me-3 size-4"
                 xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 fill="none"
                 stroke="currentColor"
                 stroke-width="2"
                 stroke-linecap="round"
                 stroke-linejoin="round">
                <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                <polyline points="9 22 9 12 15 12 15 22"></polyline>
            </svg>
            Faculty and Staff
        </a>
        <svg class="flex-shrink-0 mx-2 overflow-visible size-4 text-gray-400"
             xmlns="http://www.w3.org/2000/svg"
             width="24"
             height="24"
             viewBox="0 0 24 24"
             fill="none"
             stroke="currentColor"
             stroke-width="2"
             stroke-linecap="round"
             stroke-linejoin="round">
            <path d="m9 18 6-6-6-6"></path>
        </svg>
    </li>
    <li class="inline-flex items-center text-sm font-semibold text-gray-800 truncate"
        aria-current="page">Bachelor of Science in Information Technology</li>
</ol>

templates/pages/dean/includes/cards.html
<div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2">
    {% for program in programs %}
        <div class="max-w-xs flex flex-col bg-white border border-t-4 border-t-primary-600 shadow-sm rounded-xl">
            <div class="inline-flex justify-between pe-4 ps-4 pt-4">
                <h2 class="text-2xl font-bold text-gray-800">{{ program.program_code }}</h2>
                <div class="hs-dropdown relative inline-flex [--placement:bottom-left]">
                    <button id="hs-split-dropdown"
                            type="button"
                            class="hs-dropdown-toggle relative -ms-[.3125rem] inline-flex items-center gap-x-2 text-sm font-semibold rounded-e-md">
                        <svg class="flex-none size-4 text-gray-600"
                             xmlns="http://www.w3.org/2000/svg"
                             width="24"
                             height="24"
                             viewBox="0 0 24 24"
                             fill="none"
                             stroke="currentColor"
                             stroke-width="2"
                             stroke-linecap="round"
                             stroke-linejoin="round">
                            <circle cx="12" cy="12" r="1" /><circle cx="12" cy="5" r="1" /><circle cx="12" cy="19" r="1" />
                        </svg>
                    </button>
                    <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden divide-y divide-gray-200 min-w-40 z-20 bg-white shadow-2xl rounded-lg p-2 mt-2"
                         aria-labelledby="hs-table-dropdown-1">
                        <div class="py-2 first:pt-0 last:pb-0">
                            <span class="block py-2 px-3 text-xs font-medium uppercase text-gray-400">Actions</span>
                            <a class="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500"
                               href="">View</a>
                            <button data-hs-overlay="#edit-program"
                                    type="button"
                                    class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                Edit
                            </button>
                        </div>
                        <div class="py-2 first:pt-0 last:pb-0">
                            <button data-hs-overlay="#delete-program"
                                    type="button"
                                    class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-red-600 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                Delete
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pe-4 ps-4">
                <p class="mt-2 text-gray-500">{{ program.program_name }}</p>
            </div>
            <div class="pb-4 pe-4 ps-4  mt-auto">
                <a class="mt-3 inline-flex items-center gap-x-1 text-sm font-semibold rounded-lg border border-transparent text-primary-600 hover:primary-blue-800 disabled:opacity-50 disabled:pointer-events-none"
                   href="{% url 'faculty:assign-faculty' %}">
                    Assign Faculty
                    <svg class="flex-shrink-0 size-4"
                         xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         fill="none"
                         stroke="currentColor"
                         stroke-width="2"
                         stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="m9 18 6-6-6-6"></path>
                    </svg>
                </a>
            </div>
        </div>
    {% endfor %}
</div>

templates/pages/dean/includes/navbar.html
<!-- ========== NAVIGATION BAR ========== -->
{% load static %}
{% include "./modals.html" %}
<header class="sticky top-0 inset-x-0 flex flex-wrap sm:justify-start sm:flex-nowrap z-[48] w-full bg-white border-b py-2.5 sm:py-4 lg:ps-64">
  <nav class="flex basis-full items-center w-full mx-auto px-4 sm:px-6">
    <div class="w-full flex items-center">
      <div class="justify-start me-5 lg:me-0 lg:hidden">
        <img class="h-10" src="{% static 'images/logo/acadsked-logo-3.png' %}">
      </div>
      <div class="flex flex-row items-center justify-end gap-2 ms-auto sm:justify-between">
        <button type="button"
                class="w-[2.375rem] h-[2.375rem] inline-flex justify-center items-center gap-x-2 font-medium rounded-full border border-transparent text-gray-700 hover:text-black disabled:opacity-50 disabled:pointer-events-none">
          <svg class="flex-shrink-0 size-4"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               viewBox="0 0 24 24"
               fill="none"
               stroke="currentColor"
               stroke-width="2"
               stroke-linecap="round"
               stroke-linejoin="round">
            <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
            <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
          </svg>
        </button>
        <div class="hs-dropdown [--placement:bottom-right] relative inline-flex">
          <button id="hs-dropdown-with-header" type="button">
            <img class="inline-block size-[38px] rounded-full ring-2 ring-white"
                 src="{% if request.user.profile_image and request.user.profile_image.url %} {{ user.profile_image.url }} {% else %} https://ui-avatars.com/api/?name={{ user.first_name|cut:" " }}{% if user.middle_name %}{{ user.middle_name|cut:" " }}{% endif %}{{ user.last_name|cut:" " }}&background=random {% endif %}"
                 alt="Image Description">
          </button>
          <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-60 bg-white shadow-md rounded-lg p-2"
               aria-labelledby="hs-dropdown-with-header">
            <div class="py-3 px-5 -m-2 bg-gray-100 rounded-t-lg">
              <p class="text-sm text-gray-500">
                {{ request.user.first_name }}
                {% if request.user.middle_name %}
                  {{ request.user.middle_name }}
                {% else %}
                {% endif %}
                {{ request.user.last_name }}
              </p>
              <p class="text-sm font-medium text-gray-700">{{ request.user.email }}</p>
            </div>
            <div class="mt-2 py-2 first:pt-0 last:pb-0">
              <a class="text-sm flex items-center gap-x-3.5 py-2 px-3 rounded-lg  text-gray-700 hover:text-black focus:ring-2 focus:ring-primary-500"
                 href="{% url 'user:profile' user_id=user.id %}">
                <svg class="flex-shrink-0 size-4"
                     xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     fill="currentColor"
                     stroke="currentColor"
                     xmlns="http://www.w3.org/2000/svg"
                     svg
                     xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 448 512">
                  <path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464H398.7c-8.9-63.3-63.3-112-129-112H178.3c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3z" />
                </svg>
              </svg>
              Profile
            </a>
            <button data-hs-overlay="#sign-out"
                    class="w-full text-sm flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-gray-700 hover:text-black focus:ring-2 focus:ring-primary-500"
                    href="#">
              <svg class="flex-shrink-0 size-4"
                   xmlns="http://www.w3.org/2000/svg"
                   width="24"
                   height="24"
                   fill="currentColor"
                   stroke="currentColor"
                   xmlns="http://www.w3.org/2000/svg"
                   viewBox="0 0 512 512">
                <path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z" />
              </svg>
              Logout
            </button>
          </div>
        </div>
      </div>
      <div class="sticky top-0 inset-x-0 z-20 lg:hidden">
        <div class="flex justify-between items-center py-2">
          <button type="button"
                  class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-x-2 rounded-lg border border-gray-200 bg-white text-gray-700 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none"
                  data-hs-overlay="#application-sidebar"
                  aria-controls="application-sidebar"
                  aria-label="Sidebar">
            <svg class="hs-collapse-open:hidden flex-shrink-0 size-4"
                 xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 fill="none"
                 stroke="currentColor"
                 stroke-width="2"
                 stroke-linecap="round"
                 stroke-linejoin="round">
              <line x1="3" x2="21" y1="6" y2="6" /><line x1="3" x2="21" y1="12" y2="12" /><line x1="3" x2="21" y1="18" y2="18" />
            </svg>
            <svg class="hs-collapse-open:block hidden flex-shrink-0 size-4"
                 xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 fill="none"
                 stroke="currentColor"
                 stroke-width="2"
                 stroke-linecap="round"
                 stroke-linejoin="round">
              <path d="M18 6 6 18" />
              <path d="m6 6 12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </nav>
</header>
<!-- ========== END HEADER ========== -->
<!-- ========== MAIN CONTENT ========== -->
<!-- Sidebar -->
<div id="application-sidebar"
     class="hs-overlay [--auto-close:lg] hs-overlay-open:translate-x-0 -translate-x-full transition-all duration-300 transform w-[260px] hidden fixed inset-y-0 start-0 z-[60] bg-white border-e border-gray-200 lg:block lg:translate-x-0 lg:end-auto lg:bottom-0  ">
  <div class="px-8 pt-4">
    <img class="h-10" src="{% static 'images/logo/acadsked-logo-3.png' %}">
  </div>
  <nav id="sidebar"
       class="hs-accordion-group p-6 w-full flex flex-col flex-wrap"
       data-hs-accordion-always-open>
    <ul class="space-y-1.5">
      <li>
        <a class="font-medium flex items-center gap-x-3.5 py-2 px-2.5 text-gray-700 rounded-lg hover:text-black"
           href="{% url 'dashboard:dashboard' %}">
          <svg class="flex-shrink-0 size-4"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               viewBox="0 0 24 24"
               fill="none"
               stroke="currentColor"
               stroke-width="2"
               stroke-linecap="round"
               stroke-linejoin="round">
            <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
            <polyline points="9 22 9 12 15 12 15 22" />
          </svg>
          Dashboard
        </a>
      </li>
      <li>
        <a class="font-medium flex items-center gap-x-3.5 py-2 px-2.5  text-gray-700 rounded-lg hover:text-black"
           href="{% url 'programs:programs' %}">
          <svg class="flex-shrink-0 mt-0.5 size-4"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               fill="currentColor"
               viewBox="0 0 576 512">
            <path d="M384 480h48c11.4 0 21.9-6 27.6-15.9l112-192c5.8-9.9 5.8-22.1 .1-32.1S555.5 224 544 224H144c-11.4 0-21.9 6-27.6 15.9L48 357.1V96c0-8.8 7.2-16 16-16H181.5c4.2 0 8.3 1.7 11.3 4.7l26.5 26.5c21 21 49.5 32.8 79.2 32.8H416c8.8 0 16 7.2 16 16v32h48V160c0-35.3-28.7-64-64-64H298.5c-17 0-33.3-6.7-45.3-18.7L226.7 50.7c-12-12-28.3-18.7-45.3-18.7H64C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H87.7 384z" />
          </svg>
          Programs
        </a>
      </li>
      <li>
        <a class="font-medium flex items-center gap-x-3.5 py-2 px-2.5 text-gray-700 rounded-lg hover:text-black"
           href="{% url 'faculty:faculty' %}">
          <svg class="flex-shrink-0 size-4"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               fill="currentColor"
               viewBox="0 0 640 512">
            <path d="M144 0a80 80 0 1 1 0 160A80 80 0 1 1 144 0zM512 0a80 80 0 1 1 0 160A80 80 0 1 1 512 0zM0 298.7C0 239.8 47.8 192 106.7 192h42.7c15.9 0 31 3.5 44.6 9.7c-1.3 7.2-1.9 14.7-1.9 22.3c0 38.2 16.8 72.5 43.3 96c-.2 0-.4 0-.7 0H21.3C9.6 320 0 310.4 0 298.7zM405.3 320c-.2 0-.4 0-.7 0c26.6-23.5 43.3-57.8 43.3-96c0-7.6-.7-15-1.9-22.3c13.6-6.3 28.7-9.7 44.6-9.7h42.7C592.2 192 640 239.8 640 298.7c0 11.8-9.6 21.3-21.3 21.3H405.3zM224 224a96 96 0 1 1 192 0 96 96 0 1 1 -192 0zM128 485.3C128 411.7 187.7 352 261.3 352H378.7C452.3 352 512 411.7 512 485.3c0 14.7-11.9 26.7-26.7 26.7H154.7c-14.7 0-26.7-11.9-26.7-26.7z" />
          </svg>
        Faculty & Staff</a>
      </li>
    </ul>
    <ul class="pt-5 mt-5 space-y-2 border-t border-gray-300">
      <li>
        <a class="font-medium flex items-center gap-x-3.5 py-2 px-2.5 text-gray-700 rounded-lg hover:text-black"
           href="{% url 'user:profile' user_id=user.id %}">
          <svg class="flex-shrink-0 size-4"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               fill="currentColor"
               viewBox="0 0 512 512">
            <path d="M495.9 166.6c3.2 8.7 .5 18.4-6.4 24.6l-43.3 39.4c1.1 8.3 1.7 16.8 1.7 25.4s-.6 17.1-1.7 25.4l43.3 39.4c6.9 6.2 9.6 15.9 6.4 24.6c-4.4 11.9-9.7 23.3-15.8 34.3l-4.7 8.1c-6.6 11-14 21.4-22.1 31.2c-5.9 7.2-15.7 9.6-24.5 6.8l-55.7-17.7c-13.4 10.3-28.2 18.9-44 25.4l-12.5 57.1c-2 9.1-9 16.3-18.2 17.8c-13.8 2.3-28 3.5-42.5 3.5s-28.7-1.2-42.5-3.5c-9.2-1.5-16.2-8.7-18.2-17.8l-12.5-57.1c-15.8-6.5-30.6-15.1-44-25.4L83.1 425.9c-8.8 2.8-18.6 .3-24.5-6.8c-8.1-9.8-15.5-20.2-22.1-31.2l-4.7-8.1c-6.1-11-11.4-22.4-15.8-34.3c-3.2-8.7-.5-18.4 6.4-24.6l43.3-39.4C64.6 273.1 64 264.6 64 256s.6-17.1 1.7-25.4L22.4 191.2c-6.9-6.2-9.6-15.9-6.4-24.6c4.4-11.9 9.7-23.3 15.8-34.3l4.7-8.1c6.6-11 14-21.4 22.1-31.2c5.9-7.2 15.7-9.6 24.5-6.8l55.7 17.7c13.4-10.3 28.2-18.9 44-25.4l12.5-57.1c2-9.1 9-16.3 18.2-17.8C227.3 1.2 241.5 0 256 0s28.7 1.2 42.5 3.5c9.2 1.5 16.2 8.7 18.2 17.8l12.5 57.1c15.8 6.5 30.6 15.1 44 25.4l55.7-17.7c8.8-2.8 18.6-.3 24.5 6.8c8.1 9.8 15.5 20.2 22.1 31.2l4.7 8.1c6.1 11 11.4 22.4 15.8 34.3zM256 336a80 80 0 1 0 0-160 80 80 0 1 0 0 160z" />
          </svg>
        Account</a>
      </li>
      <li>
        <button data-hs-overlay="#sign-out"
                class="w-full font-medium flex items-center gap-x-3.5 py-2 px-2.5 text-gray-700 rounded-lg hover:text-black">
          <svg class="flex-shrink-0 size-4"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               fill="currentColor"
               viewBox="0 0 512 512">
            <path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z" />
          </svg>
          Logout
        </button>
      </li>
    </ul>
  </nav>
</div>
{% include "partials/_logout_modal.html" %}