apps/curriculum/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'curriculum'

urlpatterns = [
    path('curriculum-maintenance-and-management/', views.curriculum_maintenance_and_management, name='curriculum_maintenance_and_management'),
    path('curriculum-maintenance-and-management/update/', views.edit_institute, name='edit_institute'),
    path('<slug:institute_slug>/<slug:program_slug>/view/', views.view_program_detail, name='view_program_detail'),
    path('<slug:institute_slug>/<slug:program_slug>/update/', views.update_program_detail, name='update_program_detail'),
    path('<slug:institute_slug>/<slug:program_slug>/add/', views.add_program_detail, name='add_program_detail'),

    # Program Chairperson
    path('<slug:program_slug>/', views.curriculum, name='curriculum'),
    path('<slug:institute_slug>/<slug:program_slug>/view/', views.view_program_detail, name='view_program_detail'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/dashboard/urls.py
from django.urls import path
from .import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('faculty-workload/<str:username>/', views.faculty_workload, name='faculty-workload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from apps.user.views import signup, verify_account
from config.views import CourseListAPIView, NotificationListView, ProtectedMediaView,  SchedulerDataAPIView, UserCoursesView, check_unique, home_redirect
from django.contrib.auth.decorators import login_required

admin.site.site_title = 'administrator'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', signup, name='signup'),
    path('accounts/verify-account/', verify_account, name='verify-account'),
    path('accounts/', include('allauth.urls')),
    path('', home_redirect, name="home_redirect"),
    path('__reload__/', include('django_browser_reload.urls')), #remove this during production
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    path('timetable/', include('apps.timetable.urls', namespace='schedules')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('institute/', include('apps.institutes.urls', namespace='institutes')),
    path('program/', include('apps.programs.urls', namespace="programs")),
    path('faculty-and-staff/', include('apps.faculty.urls', namespace="faculty")),
    path("__debug__/", include("debug_toolbar.urls")), #remove this during production
    path('check-unique/', check_unique, name='check_unique'),

    #Django Rest Framework
    path('api/courses/', CourseListAPIView.as_view(), name='course_list_api'),
    path('api/courses/<int:member_id>', UserCoursesView.as_view(), name='instructor_assigned_courses'),
    path('api/prepare-ga-data/<int:user_group_id>/', SchedulerDataAPIView.as_view(), name='prepare-ga-data'),
    path('api/notifications/', NotificationListView.as_view(), name='notification-list'),

    #Protected Media
    path('media/<path:path>', login_required(ProtectedMediaView.as_view()), name='protected_media'),
]   
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/curriculum/models.py
from django.db import models
from django.utils.text import slugify
from apps.institutes.models import Institutes
from django.db.models import UniqueConstraint

class Programs(models.Model):
    program_id = models.AutoField(primary_key=True)
    program_code = models.CharField(max_length=100, unique=True, null=False)
    program_name = models.CharField(max_length=255, unique=True, null=False)
    program_slug = models.SlugField(max_length=255, unique=True, null=False)
    institute = models.ForeignKey(Institutes, on_delete=models.CASCADE, null=False)

    class Meta:  
        db_table = "programs"
        verbose_name = 'Program'
        verbose_name_plural = 'Programs'
    
    def __str__(self):
        return self.program_name
    
    def save(self, *args, **kwargs):
        if not self.program_slug:
            self.program_slug = slugify(self.program_name)
        super().save(*args, **kwargs)
        
class CurriculumYear(models.Model):
    curriculum_id = models.AutoField(primary_key=True)
    curriculum_year = models.CharField(max_length=255)
    institute = models.ForeignKey(Institutes, on_delete=models.CASCADE)
    program = models.ForeignKey(Programs, on_delete=models.CASCADE)

    class Meta:
        db_table = "curriculum_year"
        verbose_name = 'Curriculum Year'
        verbose_name_plural = 'Curriculum Year'
        constraints = [
            UniqueConstraint(fields=['curriculum_year', 'institute', 'program'], name='unique_curriculum_year_institute_program')
        ]
    
    def save(self, *args, **kwargs):
        # Check if a CurriculumYear with the same name, institute, and program already exists
        original_name = self.curriculum_year
        if CurriculumYear.objects.filter(
            curriculum_year=self.curriculum_year,
            institute=self.institute,
            program=self.program
        ).exists():
            counter = 1  # Start numbering from 1
            while CurriculumYear.objects.filter(
                curriculum_year=f"{original_name} ({counter})",
                institute=self.institute,
                program=self.program
            ).exists():
                counter += 1
            self.curriculum_year = f"{original_name} ({counter})"
        
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.curriculum_year} - {self.program} - {self.institute}"
    

class Rooms(models.Model):
    room_id = models.AutoField(primary_key=True)
    room_name = models.CharField(max_length=100, unique=True)
    is_lab = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    building = models.CharField(max_length=100, null=True, blank=True)
    
    class Meta:  
        db_table = "rooms"
        verbose_name = 'Classroom'
        verbose_name_plural = 'Classrooms'
    
    def __str__(self):
        return self.room_name

class Courses(models.Model):
    course_id = models.AutoField(primary_key=True)
    program = models.ForeignKey(Programs, on_delete=models.CASCADE, max_length=50)
    curriculum = models.ForeignKey(CurriculumYear, on_delete=models.CASCADE)
    course_code = models.CharField(max_length=10)
    course_description = models.TextField(max_length=100)
    lecture = models.IntegerField(default=0) 
    laboratory = models.IntegerField(default=0)
    credit_units = models.IntegerField(default=0)
    semester = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_lab = models.BooleanField(default=False)
    year_level = models.IntegerField(default=1)

    class Meta:  
        db_table = "courses"
        verbose_name = 'course'
        verbose_name_plural = 'courses'
    
    def __str__(self):
        return self.course_code

apps/curriculum/views.py
from collections import defaultdict
from django.contrib import messages
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.text import slugify
from apps.curriculum.forms import CopyCurriculumForm, ProgramForm
from apps.curriculum.forms import  CurriculumYearForm
from apps.curriculum.models import CurriculumYear, Programs, Courses
from django.contrib.auth.decorators import login_required
from apps.institutes.models import Institutes
from apps.user.utils import get_template_by_user_type
from django.db.models import Count
from django.db import IntegrityError

# ============================================= START FOR REGISTRAR VIEW =============================================
@login_required
def edit_institute(request):
    template = get_template_by_user_type(request.user, 'edit-institute')
    institutes = Institutes.objects.all()
    
    if 'UpdateInstituteSubmit' in request.POST:
        updated_institutes = []
        for institute in institutes:
            institute_id = request.POST.get(f'institute_id_{institute.institute_id}')
            institute_code = request.POST.get(f'acronym_{institute.institute_id}')
            institute_name = request.POST.get(f'institute_name_{institute.institute_id}')
            
            if institute_id and institute_code and institute_name:
                # Generate slug from institute name
                new_slug = slugify(institute_name)
                
                # Check if there are any changes to the institute's data
                if (
                    institute.acronym != institute_code or
                    institute.institute_name != institute_name or
                    institute.institute_slug != new_slug
                ):
                    institute.acronym = institute_code
                    institute.institute_name = institute_name
                    institute.institute_slug = new_slug
                    updated_institutes.append(institute)
        
        if updated_institutes:
            # Update only if there are changes
            Institutes.objects.bulk_update(updated_institutes, ['acronym', 'institute_name', 'institute_slug'])
            messages.success(request, 'Institutes updated successfully.')
        else:
            messages.info(request, 'No updates were made.')
    
        return redirect('curriculum:curriculum_maintenance_and_management')
    
    if template and request.user.user_type in [1]:
        return render(request, template, {'institutes': institutes})
    raise Http404("Access denied")


def group_courses_by_year_and_semester(courses):
    grouped_courses = defaultdict(lambda: defaultdict(list))
    totals = defaultdict(lambda: defaultdict(lambda: {'lecture': 0, 'lab': 0, 'credit_units': 0}))
    overall_totals = {'lecture': 0, 'lab': 0, 'credit_units': 0, 'courses': 0}

    for course in courses:
        year_level_display = {
            1: 'First Year',
            2: 'Second Year',
            3: 'Third Year',
            4: 'Fourth Year',
        }.get(course.year_level, f'Year {course.year_level}')

        semester_display = {
            1: '1st Semester',
            2: '2nd Semester',
            3: '3rd Semester',
        }.get(course.semester, f'{course.semester}th Semester')

        grouped_courses[year_level_display][semester_display].append(course)
        totals[year_level_display][semester_display]['lecture'] += course.lecture
        totals[year_level_display][semester_display]['lab'] += course.laboratory
        totals[year_level_display][semester_display]['credit_units'] += course.credit_units
        overall_totals['lecture'] += course.lecture
        overall_totals['lab'] += course.laboratory
        overall_totals['credit_units'] += course.credit_units
        overall_totals['courses'] += 1

    return grouped_courses, totals, overall_totals

@login_required
def curriculum_maintenance_and_management(request):
    # Get the template based on user type
    template = get_template_by_user_type(request.user, 'programs')
    # Fetch all institutes with related programs
    institutes = Institutes.objects.prefetch_related('programs_set').all()

    # Determine the most recent curriculum ID for each program
    for institute in institutes:
        for program in institute.programs_set.all():
            curriculum_with_courses = CurriculumYear.objects.filter(
                courses__program=program
            ).order_by('-curriculum_id').first()
            
            if curriculum_with_courses:
                program.curriculum_id = curriculum_with_courses.curriculum_id
            else:
                # No curriculum found, set a flag or handle accordingly
                program.curriculum_id = None  # Or set to a default value if needed
                
    if request.method == 'POST':
        program_form = ProgramForm(request.POST)

        # Handle program submission
        if 'AddProgramSubmit' in request.POST:
            if program_form.is_valid():
                program = program_form.save()
                institute = get_object_or_404(Institutes, pk=program.institute.pk)
                messages.success(request, f'Program successfully added to {institute.institute_name}.')
                return redirect(request.path)
            else:
                messages.error(request, 'An unexpected error occurred while adding a program.')
                return redirect(request.path)
        
        # Handle institute submission
        elif 'AddInstituteSubmit' in request.POST:
            new_institute_code = request.POST.get('institute_code')
            new_institute_name = request.POST.get('institute_name')
            
            if new_institute_code and new_institute_name:
                new_institute_slug = slugify(new_institute_name)
                
                # Check if an institute with the same acronym or name already exists
                if not Institutes.objects.filter(acronym=new_institute_code, institute_name=new_institute_name).exists():
                    # Create and save the new institute
                    new_institute = Institutes(
                        acronym=new_institute_code,
                        institute_name=new_institute_name,
                        institute_slug=new_institute_slug
                    )
                    new_institute.save()
                    messages.success(request, 'New institute created successfully.')
                else:
                    messages.error(request, 'An institute with this code or name already exists.')
            else:
                messages.error(request, 'Both institute code and name are required.')
            return redirect(request.path)

    else:
        program_form = ProgramForm()

    if template and request.user.user_type in [1]:
        context = {
            'institutes': institutes,
            'program_form': program_form,
        }
        return render(request, template, context)

    return HttpResponseForbidden("Access denied")

def change_program_name(program_id, program_code, program_name):
    program = Programs.objects.get(pk=program_id)
    program.program_code = program_code
    program.program_name = program_name
    program.save()
    return {'success': True}

def update_course(course_id, course_code, course_description, lecture, laboratory, semester, year_level):
    course = get_object_or_404(Courses, course_id=course_id)
    course.course_code = course_code
    course.course_description = course_description
    course.lecture = lecture
    course.laboratory = laboratory
    course.semester = semester
    course.year_level = year_level
    course.save()
    return {'success': True}

def delete_course(course_id):
    course = get_object_or_404(Courses, course_id=course_id)
    course.delete()
    return {'success': True}


def construct_curriculum_url(institute_slug, program_slug, curriculum_id):
    if institute_slug:
        url = reverse('curriculum:view_program_detail', kwargs={
            'institute_slug': institute_slug,
            'program_slug': program_slug
        })
    else:
        url = reverse('curriculum:curriculum', kwargs={
            'program_slug': program_slug
        })
    return f"{url}?curriculum={curriculum_id}"

@login_required
def view_program_detail(request, institute_slug, program_slug):
    template = get_template_by_user_type(request.user, 'view-program-detail')
    institute = get_object_or_404(Institutes, institute_slug=institute_slug)
    program = get_object_or_404(Programs, program_slug=program_slug, institute=institute)
    current_curriculum_id = request.GET.get('curriculum')
    program_id = program.pk
          
    if request.method == 'POST':
        if 'changeProgramNameSubmit' in request.POST:
            program_id = program.program_id
            program_code = request.POST.get('program_code')
            program_name = request.POST.get('program_name')

            # Check if the data has changed
            curriculum_id = request.GET.get('curriculum', '')
            if program.program_code == program_code and program.program_name == program_name:
                messages.info(request, 'No changes have been made.')
                return redirect(construct_curriculum_url(institute_slug, program_slug, curriculum_id))
            else:
                try:
                    update_result = change_program_name(program_id, program_code, program_name)
                    if update_result['success']:
                        messages.success(request, 'Successfully updated the program.')
                        return redirect(construct_curriculum_url(institute_slug, program_slug, curriculum_id))
                    else:
                        messages.error(request, 'Failed to update the program.')
                except IntegrityError as e:
                    error_message = str(e)

templates/pages/progchair/dashboard.html
{% extends "_base.html" %}
{% load compress %}
{% load static %}
{% block title %}
  Dashboard
{% endblock title %}
{% block content %}
  {% include "./includes/_navbar.html" %}
  <div class="w-full lg:ps-64 bg-gray-100 h-full">
    <div class="p-6 space-y-3">
      {% comment %} <p class="text-2xl font-extrabold text-gray-900 uppercase">{{ greeting_message }}, {{ request.user.first_name }} 👋</p> {% endcomment %}
      <div class="bg-gray-50 border border-gray-200 text-sm text-gray-600 rounded-lg p-4"
           role="alert"
           tabindex="-1"
           aria-labelledby="hs-link-on-right-label">
        <p class="text-2xl font-extrabold text-gray-900 uppercase">
          {{ institute.institute_name }} ({{ institute.acronym }})
          {% if selected_group %}
            <span>&nbsp-&nbsp{{ selected_group.group_name }} ({{ selected_group.get_semester_display }})</span>
          {% else %}
          {% endif %}
        </p>
      </div>
      <div class=" bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
        <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200">
          <div class="sm:col-span-1">
            <label for="search-instructor" class="sr-only">Search</label>
            <div class="relative">
              <input type="text"
                     id="search-instructor"
                     name="search-instructor"
                     autocomplete="off"
                     maxlength="50"
                     class="py-2 px-3 ps-11 block w-full border-gray-200 rounded-lg text-sm focus:border-primary-500 focus:ring-primary-500 disabled:opacity-50 disabled:pointer-events-none"
                     placeholder="Search">
              <div class="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-4">
                <svg class="size-4 text-gray-400"
                     xmlns="http://www.w3.org/2000/svg"
                     width="16"
                     height="16"
                     fill="currentColor"
                     viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                </svg>
              </div>
            </div>
          </div>
          <div class="sm:col-span-2">
            <div class="hs-dropdown relative inline-flex">
              <button id="hs-dropdown-toggle"
                      type="button"
                      class="hs-dropdown-toggle py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none"
                      aria-haspopup="menu"
                      aria-expanded="false"
                      aria-label="Dropdown">
                {% if selected_group %}
                  <span>{{ selected_group.group_name }} ({{ selected_group.get_semester_display }})</span>
                {% else %}
                  <span>Select group</span>
                {% endif %}
                <svg class="hs-dropdown-open:rotate-180 size-4"
                     xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor"
                     stroke-width="2"
                     stroke-linecap="round"
                     stroke-linejoin="round">
                  <path d="m6 9 6 6 6-6" />
                </svg>
              </button>
              <div class="hs-dropdown-menu min-w-48 transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden z-10">
                <div class="hs-dropdown-open:ease-in hs-dropdown-open:opacity-100 hs-dropdown-open:scale-100 transition ease-out opacity-0 scale-95 duration-200 mt-2 origin-top-left min-w-48 bg-white shadow-md rounded-lg p-2"
                     data-hs-transition>
                  <span class="block py-2 px-3 text-xs font-medium uppercase text-gray-400">Options</span>
                  {% if all_groups.exists %}
                    {% for group in all_groups %}
                      <a class="flex justify-between items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100"
                         href="?group={{ group.group_id }}&page={{ request.GET.page|default:1 }}&items_per_page={{ request.GET.items_per_page|default:25 }}">
                        <span>{{ group.group_name }} ({{ group.get_semester_display }})</span>
                        {% if group.group_id == selected_group.group_id %}
                          <svg class="shrink-0 size-3.5 text-gray-800"
                               xmlns="http://www.w3.org/2000/svg"
                               width="24"
                               height="24"
                               viewBox="0 0 24 24"
                               fill="none"
                               stroke="currentColor"
                               stroke-width="2"
                               stroke-linecap="round"
                               stroke-linejoin="round">
                            <path d="M20 6 9 17l-5-5"></path>
                          </svg>
                        {% endif %}
                      </a>
                    {% endfor %}
                  {% else %}
                    <div class="flex justify-between items-center py-2 px-3 text-sm text-gray-800">
                      <span class="text-sm text-gray-500">No groups available.</span>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="inline-flex gap-x-2">
              <button data-hs-overlay="#"
                      type="button"
                      class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-50 disabled:pointer-events-none">
                Download All
              </button>
            </div>
          </div>
        </div>
        <div id="results-container">
          {% if faculty_and_staff %}
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-3 px-6">
              {% for user in faculty_and_staff %}
                <div class="flex flex-col rounded-xl p-4 md:p-6 bg-white border border-gray-200">
                  <div class="flex items-center gap-x-4">
                    <img class="inline-block flex-shrink-0 size-[62px] rounded-full"
                         src="{% if user.profile_image and user.profile_image.url %}{{ user.profile_image.url }}{% else %}https://ui-avatars.com/api/?name={{ user.first_name|cut:' ' }}{% if user.middle_name %}{{ user.middle_name|cut:' ' }}{% endif %}{{ user.last_name|cut:' ' }}&background=random{% endif %}"
                         alt="Image Description">
                    <div class="grow">
                      <h3 class="font-medium text-gray-800 uppercase">
                        {{ user.first_name }}
                        {% if user.middle_name %}
                          {{ user.middle_name }}
                        {% else %}
                        {% endif %}
                        {{ user.last_name }}
                      </h3>
                      <p class="text-sm text-gray-500 lowercase">{{ user.email }}</p>
                    </div>
                  </div>
                  <!-- Social Brands -->
                  <div class="mt-3 space-x-1">
                    <a class="inline-flex items-center gap-x-1 text-sm font-semibold rounded-lg border border-transparent text-primary-600 hover:primary-blue-800 disabled:opacity-50 disabled:pointer-events-none"
                       href="{% url 'dashboard:faculty-workload'  user.username %}">
                      Faculty Workload
                      <svg class="flex-shrink-0 size-4"
                           xmlns="http://www.w3.org/2000/svg"
                           width="24"
                           height="24"
                           viewBox="0 0 24 24"
                           fill="none"
                           stroke="currentColor"
                           stroke-width="2"
                           stroke-linecap="round"
                           stroke-linejoin="round">
                        <path d="m9 18 6-6-6-6"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              {% endfor %}
            </div>
          {% else %}
            <div class="min-h-60 flex flex-col mt-2">{% include "partials/_no_data.html" %}</div>
          {% endif %}
        </div>
        <div class="px-6 py-4 flex justify-between md:items-center mt-4 border-t border-gray-200">
          <div>
            <p class="text-sm text-gray-600">
              <span class="font-semibold text-gray-800">{{ total_users }}</span> results
            </p>
          </div>
          <div>
            <div class="inline-flex gap-x-2">
              {% include "partials/_page_per_item.html" %}
              {% if faculty_and_staff.has_previous %}
                <a href="?group={{ selected_group.group_id }}&page={{ faculty_and_staff.previous_page_number }}&items_per_page={{ request.GET.items_per_page }}"
                   class="py-1.5 px-2 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none">
                  <svg class="flex-shrink-0 size-4"
                       xmlns="http://www.w3.org/2000/svg"
                       width="24"
                       height="24"
                       viewBox="0 0 24 24"
                       fill="none"
                       stroke="currentColor"
                       stroke-width="2"
                       stroke-linecap="round"
                       stroke-linejoin="round">
                    <path d="m15 18-6-6 6-6" />
                  </svg>
                  Prev
                </a>
              {% else %}
                <button type="button"
                        class="disabled py-1.5 px-2 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-gray-200 text-gray-800 shadow-sm ">
                  <svg class="flex-shrink-0 size-4"
                       xmlns="http://www.w3.org/2000/svg"
                       width="24"
                       height="24"
                       viewBox="0 0 24 24"
                       fill="none"
                       stroke="currentColor"
                       stroke-width="2"
                       stroke-linecap="round"
                       stroke-linejoin="round">
                    <path d="m15 18-6-6 6-6" />
                  </svg>
                  Prev
                </button>
              {% endif %}
              {% if faculty_and_staff.has_next %}
                <a href="?group={{ selected_group.group_id }}&page={{ faculty_and_staff.next_page_number }}&items_per_page={{ request.GET.items_per_page }}"
                   class="py-1.5 px-2 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none">
                  Next
                  <svg class="flex-shrink-0 size-4"
                       xmlns="http://www.w3.org/2000/svg"
                       width="24"
                       height="24"
                       viewBox="0 0 24 24"
                       fill="none"
                       stroke="currentColor"
                       stroke-width="2"
                       stroke-linecap="round"
                       stroke-linejoin="round">
                    <path d="m9 18 6-6-6-6" />
                  </svg>
                </a>
              {% else %}
                <button type="button"
                        class="disabled py-1.5 px-2 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-gray-200 text-gray-800 shadow-sm ">
                  <svg class="flex-shrink-0 size-4"
                       xmlns="http://www.w3.org/2000/svg"
                       width="24"
                       height="24"
                       viewBox="0 0 24 24"
                       fill="none"
                       stroke="currentColor"
                       stroke-width="2"
                       stroke-linecap="round"
                       stroke-linejoin="round">
                    <path d="m9 18 6-6-6-6" />
                  </svg>
                  Next
                </button>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.getElementById('search-instructor').addEventListener('input', function() {
        const searchTerm = this.value.trim();
        const groupId = '{{ group_id }}';

        // Perform AJAX request to the view
        fetch(`{% url 'dashboard:dashboard' %}?search=${encodeURIComponent(searchTerm)}&group=${groupId}`, {
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
        .then(response => response.text())
        .then(data => {
            // Update the results container with the filtered data
            document.getElementById('results-container').innerHTML = data;
        })
        .catch(error => {
            console.error('Error fetching search results:', error);
        });
    });
  </script>
{% endblock content %}