apps/dashboard/urls.py
from django.urls import path
from .import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('faculty-workload/<str:username>/', views.faculty_workload, name='faculty-workload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/faculty/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'faculty'

urlpatterns = [
    path('', views.faculty, name='faculty'),  
    path('faculty-workload/', views.faculty_workload, name='faculty-workload'),  
    path('assign-faculty/', views.assign_faculty, name='assign-faculty'),  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/programs/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'programs'

urlpatterns = [
     path('', views.programs, name='programs'),
     path('curriculum-version/', views.curriculum_version, name='curriculum-version'),
     path('curriculum-version/courses/', views.courses, name='courses'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from apps.user.views import signup, verify_account
from config.views import CourseListAPIView, NotificationListView, ProtectedMediaView,  SchedulerDataAPIView, UserCoursesView, check_unique, home_redirect
from django.contrib.auth.decorators import login_required

admin.site.site_title = 'administrator'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', signup, name='signup'),
    path('accounts/verify-account/', verify_account, name='verify-account'),
    path('accounts/', include('allauth.urls')),
    path('', home_redirect, name="home_redirect"),
    path('__reload__/', include('django_browser_reload.urls')), #remove this during production
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    path('timetable/', include('apps.timetable.urls', namespace='schedules')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('institute/', include('apps.institutes.urls', namespace='institutes')),
    path('program/', include('apps.programs.urls', namespace="programs")),
    path('faculty-and-staff/', include('apps.faculty.urls', namespace="faculty")),
    path("__debug__/", include("debug_toolbar.urls")), #remove this during production
    path('check-unique/', check_unique, name='check_unique'),

    #Django Rest Framework
    path('api/courses/', CourseListAPIView.as_view(), name='course_list_api'),
    path('api/courses/<int:member_id>', UserCoursesView.as_view(), name='instructor_assigned_courses'),
    path('api/prepare-ga-data/<int:user_group_id>/', SchedulerDataAPIView.as_view(), name='prepare-ga-data'),
    path('api/notifications/', NotificationListView.as_view(), name='notification-list'),

    #Protected Media
    path('media/<path:path>', login_required(ProtectedMediaView.as_view()), name='protected_media'),
]   
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/faculty/models.py
from django.db import models

# Create your models here.

apps/institutes/models.py
from django.db import models
from django.utils.text import slugify

class Institutes(models.Model):
    institute_id = models.AutoField(primary_key=True)
    institute_name = models.CharField(max_length=100, unique=True, null=False)
    acronym = models.CharField(max_length=50, unique=True, null=False)
    institute_slug = models.SlugField(max_length=255, unique=True, null=False)

    class Meta:
        db_table = "institutes"
        verbose_name = 'Institute'
        verbose_name_plural = 'Institutes'

    def __str__(self):
        return self.institute_name
    
    def save(self, *args, **kwargs):
            if not self.institute_slug:
                self.institute_slug = slugify(self.institute_name)
            super().save(*args, **kwargs)

apps/programs/models.py
from django.db import models

# Create your models here.

apps/institutes/forms.py
from django import forms
from .models import Institutes

class InstitutesForm(forms.ModelForm):
    class Meta:
        model = Institutes
        fields = ['institute_name', 'acronym']

apps/programs/forms.py
from django import forms
from apps.curriculum.models import Courses, Programs

class ProgramForm(forms.ModelForm):
    class Meta:
        model = Programs
        fields = ['program_name', 'program_code']

class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ['course_code', 'course_description', 'year_level','semester','lecture', 'laboratory', 'program']

apps/dashboard/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from apps.curriculum.models import CurriculumYear, Programs
from apps.dashboard.common.greeting_message_services import GreetingMessage
from apps.institutes.models import Institutes
from apps.timetable.common.item_per_page_utils import validate_items_per_page
from apps.user.models import User
from apps.user.utils import get_template_by_user_type
from apps.user.common.group_members_utils import get_faculty_and_staff_info

@login_required
def dashboard(request):
    template = get_template_by_user_type(request.user, 'dashboard')
    
    # Greeting Message
    greeting_service = GreetingMessage()
    greeting_message = greeting_service.get_greeting_message()

    if template and request.user.user_type in [4]:
        institute = get_object_or_404(Institutes, user=request.user)
        program = get_object_or_404(Programs, user=request.user)
        curriculum_with_courses = CurriculumYear.objects.filter(
          courses__program=program
        ).order_by('-curriculum_id').first()
        
        if curriculum_with_courses:
          request.session['curriculum_id'] = curriculum_with_courses.curriculum_id
          program.curriculum_id = curriculum_with_courses.curriculum_id
        else:
          # No curriculum found, set a flag or handle accordingly
          program.curriculum_id = None  # Or set to a default value if needed
      
        user_info = get_faculty_and_staff_info(request)

        items_per_page = request.GET.get('items_per_page', 25)
        page_number = request.GET.get('page', 1)
        group_id = request.GET.get('group', None)

        # Validate items per page
        validated_items_per_page = validate_items_per_page(items_per_page, request, page_number, group_id)
        if isinstance(validated_items_per_page, HttpResponseRedirect):
            return validated_items_per_page
        # Update items per page
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            # If AJAX request, return only the partial template
            return HttpResponse(render(request, 'partials/_faculty_staff_list.html', {
                'faculty_and_staff': user_info['faculty_and_staff'],
            }).content)
        
        # If standard request, return the full dashboard template
        return render(request, template, {
            **user_info,
            'greeting_message': greeting_message,
            'institute': institute,
        })
    
    elif template and request.user.user_type in [1, 2, 3]:
        return render(request, template)
    
    else:
        raise Http404("Template not found")

@login_required
def faculty_workload(request, username):
    template = get_template_by_user_type(request.user, 'faculty-workload')
    user = get_object_or_404(User, username=username)
    if template and request.user.user_type in [3, 4]:
            faculty_and_staff = User.objects.filter(institute=request.user.institute,program=request.user.program)
            program_name = request.user.program.program_name
            program_code = request.user.program.program_code
            institute_name = request.user.institute.institute_name
            return render(request, template, {
                'faculty_and_staff': faculty_and_staff,
                'program_name': program_name,
                'institute_name': institute_name,
                'program_code': program_code,
                'user': user,
            })
    raise Http404("Template not found")

apps/faculty/views.py
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from apps.curriculum.models import Programs
from apps.user.utils import get_template_by_user_type


@login_required
def faculty(request):
    programs = Programs.objects.all()
    template = get_template_by_user_type(request.user, 'faculty')
    if template and request.user.user_type == 2 or 3:
        return render(request, template, {'programs': programs})
    raise Http404

@login_required
def faculty_workload(request):
    template = get_template_by_user_type(request.user, 'faculty-workload')
    if template and request.user.user_type == 2:
        return render(request, template)
    raise Http404

@login_required
def assign_faculty(request):
    template = get_template_by_user_type(request.user, 'assign-faculty')
    if template and request.user.user_type == 3:
        return render(request, template)
    raise Http404

apps/institutes/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from apps.institutes.forms import InstitutesForm
from .models import Institutes
from apps.curriculum.models import Programs
from apps.user.utils import get_template_by_user_type

@login_required
def institute(request):
     #Add Institute
    if request.method == 'POST':
        form = InstitutesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('institutes:list-of-institute')
    else:
        form = InstitutesForm()

    institutes = Institutes.objects.all()
    template = get_template_by_user_type(request.user, 'institutes')
    if template and request.user.user_type in [1,2]:
        return render(request, template, {'institutes': institutes})
    raise Http404

@login_required
def assign_faculty(request):
    template = get_template_by_user_type(request.user, 'assign-faculty')
    if template and request.user.user_type in [1,2]:
        return render(request, template)
    raise Http404

apps/programs/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from apps.programs.forms import CoursesForm, ProgramForm
from apps.curriculum.forms import CurriculumYearForm
from apps.curriculum.models import Courses, CurriculumYear, Programs
from apps.user.utils import get_template_by_user_type

@login_required
def programs(request):
    if request.method == 'POST':
        form = ProgramForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('programs:programs')
    else:
        form = ProgramForm()

    programs = Programs.objects.all()
    template = get_template_by_user_type(request.user, 'programs')
    if template and request.user.user_type == 2 or 3:
        return render(request, template, {'programs': programs, 'form': form})
    raise Http404

@login_required
def courses(request):
    if request.method == 'POST':
        form = CoursesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('programs:courses')
    else:
        form = CoursesForm()

    courses = Courses.objects.all()
    template = get_template_by_user_type(request.user, 'courses')
    if template and request.user.user_type == 3:
        return render(request, template, {'courses': courses, 'form': form})
    raise Http404

@login_required
def curriculum_version(request):
    # Add Currilum Versions
    if request.method == 'POST':
        form = CurriculumYearForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('programs:curriculum-version')
    else:
        form = CurriculumYearForm()
        
    curriculum_versions = CurriculumYear.objects.all()
    template = get_template_by_user_type(request.user, 'curriculum-version')
    if template and request.user.user_type == 3:
        return render(request, template, {'curriculum_versions': curriculum_versions, 'form': form})
    raise Http404

templates/pages/vpaa/academic-year.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
    Academic Year
{% endblock title %}
{% block content %}
    {% include "./includes/navbar.html" %}
    <div class="w-full lg:ps-64 bg-gray-100 h-full">
        <div class="p-6 space-y-3">
            <p class="text-2xl font-extrabold text-gray-900">Institute of Computing</p>

            <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2">
                <button data-hs-overlay="#add-institute"
                        type="button"
                        class="flex flex-col items-center justify-center  max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100  text-gray-500 ">
                    <svg class="w-8 m-2"
                         fill="currentColor"
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         viewBox="0 0 512 512">
                        <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344V280H168c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V168c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H280v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z" />
                    </svg>
                    <p class="mb-3 font-normal text-gray-500 0">Create Academic Year</p>
                </button>
                <div class="max-w-xs flex flex-col  bg-white border border-t-4 border-t-primary-600 shadow-sm rounded-xl">
                    <div class="inline-flex justify-between pe-4 ps-4 pt-4">
                        <h2 class="text-2xl font-bold text-gray-800">1st Semester</h2>
                        <div class="hs-dropdown relative inline-flex [--placement:bottom-left]">
                            <button id="hs-split-dropdown"
                                    type="button"
                                    class="hs-dropdown-toggle relative -ms-[.3125rem] inline-flex items-center gap-x-2 text-sm font-semibold rounded-e-md">
                                <svg class="flex-none size-4 text-gray-600"
                                     xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24"
                                     viewBox="0 0 24 24"
                                     fill="none"
                                     stroke="currentColor"
                                     stroke-width="2"
                                     stroke-linecap="round"
                                     stroke-linejoin="round">
                                    <circle cx="12" cy="12" r="1" /><circle cx="12" cy="5" r="1" /><circle cx="12" cy="19" r="1" />
                                </svg>
                            </button>
                            <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden divide-y divide-gray-200 min-w-40 z-20 bg-white shadow-2xl rounded-lg p-2 mt-2"
                                 aria-labelledby="hs-table-dropdown-1">
                                <div class="py-2 first:pt-0 last:pb-0">
                                    <span class="block py-2 px-3 text-xs font-medium uppercase text-gray-400">Actions</span>
                                    <a class="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500"
                                       href="#">View</a>
                                    <button data-hs-overlay="#edit-institute"
                                            type="button"
                                            class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                        Edit
                                    </button>
                                </div>
                                <div class="py-2 first:pt-0 last:pb-0">
                                    <button data-hs-overlay="#delete-institute"
                                            type="button"
                                            class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-red-600 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                        Delete
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pe-4 ps-4">
                        <h2 class="text-2xl font-bold text-gray-800">2024-2025</h2>
                    </div>
                    <div class="pb-4 pe-4 ps-4 mt-auto">
                        <a class=" mt-3  inline-flex items-center gap-x-1 text-sm font-semibold rounded-lg border border-transparent text-primary-600 hover:primary-blue-800 disabled:opacity-50 disabled:pointer-events-none"
                           href="#">
                            Assign Faculty
                            <svg class="flex-shrink-0 size-4"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 fill="none"
                                 stroke="currentColor"
                                 stroke-width="2"
                                 stroke-linecap="round"
                                 stroke-linejoin="round">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="max-w-xs flex flex-col  bg-white border border-t-4 border-t-primary-600 shadow-sm rounded-xl">
                    <div class="inline-flex justify-between pe-4 ps-4 pt-4">
                        <h2 class="text-2xl font-bold text-gray-800">2nd Semester</h2>
                        <div class="hs-dropdown relative inline-flex [--placement:bottom-left]">
                            <button id="hs-split-dropdown"
                                    type="button"
                                    class="hs-dropdown-toggle relative -ms-[.3125rem] inline-flex items-center gap-x-2 text-sm font-semibold rounded-e-md">
                                <svg class="flex-none size-4 text-gray-600"
                                     xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24"
                                     viewBox="0 0 24 24"
                                     fill="none"
                                     stroke="currentColor"
                                     stroke-width="2"
                                     stroke-linecap="round"
                                     stroke-linejoin="round">
                                    <circle cx="12" cy="12" r="1" /><circle cx="12" cy="5" r="1" /><circle cx="12" cy="19" r="1" />
                                </svg>
                            </button>
                            <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden divide-y divide-gray-200 min-w-40 z-20 bg-white shadow-2xl rounded-lg p-2 mt-2"
                                 aria-labelledby="hs-table-dropdown-1">
                                <div class="py-2 first:pt-0 last:pb-0">
                                    <span class="block py-2 px-3 text-xs font-medium uppercase text-gray-400">Actions</span>
                                    <a class="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500"
                                       href="#">View</a>
                                    <button data-hs-overlay="#edit-institute"
                                            type="button"
                                            class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                        Edit
                                    </button>
                                </div>
                                <div class="py-2 first:pt-0 last:pb-0">
                                    <button data-hs-overlay="#delete-institute"
                                            type="button"
                                            class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-red-600 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                        Delete
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pe-4 ps-4">
                        <h2 class="text-2xl font-bold text-gray-800">2024-2025</h2>
                    </div>
                    <div class="pb-4 pe-4 ps-4 mt-auto">
                        <a class=" mt-3  inline-flex items-center gap-x-1 text-sm font-semibold rounded-lg border border-transparent text-primary-600 hover:primary-blue-800 disabled:opacity-50 disabled:pointer-events-none"
                           href="#">
                            Assign Faculty
                            <svg class="flex-shrink-0 size-4"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 fill="none"
                                 stroke="currentColor"
                                 stroke-width="2"
                                 stroke-linecap="round"
                                 stroke-linejoin="round">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/pages/vpaa/assign-faculty.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
    Institute of Computing
{% endblock title %}
{% block content %}
    {% include "./includes/navbar.html" %}
    <div class="w-full lg:ps-64 bg-gray-100 h-full">
        <div class="p-6 space-y-3">
            <p class="text-2xl font-extrabold text-gray-900">Institute of Computing</p>
            {% include "./includes/breadcrumb.html" %}
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                {% include "./includes/form-asign-faculty.html" %}
                {% include "./includes/table-asigned-faculty.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/vpaa/dashboard.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
  Dashboard
{% endblock title %}
{% block content %}
  {% include "./includes/navbar.html" %}
  <div class="w-full lg:ps-64 bg-gray-100 h-full">
    <div class="p-6 space-y-3">
      <p class="text-2xl font-extrabold text-gray-900">Welcome back, {{ request.user.first_name }}!</p>
      <div class="px-6 py-4 bg-white border rounded-lg">{% include "./includes/cards-instructors.html" %}</div>
    </div>
  </div>
{% endblock content %}

templates/pages/vpaa/institutes.html
{% extends "_base.html" %}
{% load static %}
{% block title %}
    Manage Institutes
{% endblock title %}
{% block content %}
    {% include "./includes/navbar.html" %}
    <div class="w-full lg:ps-64 bg-gray-100 h-full">
        <div class="p-6 space-y-3">
            <p class="text-2xl font-extrabold text-gray-900">Manage Institutes</p>
            <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2">
                <button data-hs-overlay="#add-institute"
                        type="button"
                        class="flex flex-col items-center justify-center  max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100  text-gray-500 ">
                    <svg class="w-8 m-2"
                         fill="currentColor"
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         viewBox="0 0 512 512">
                        <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344V280H168c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V168c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H280v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z" />
                    </svg>
                    <p class="mb-3 font-normal text-gray-500 0">Add Institute</p>
                </button>
                {% for institute in institutes %}
                    <div class="max-w-xs flex flex-col  bg-white border border-t-4 border-t-primary-600 shadow-sm rounded-xl">
                        <div class="inline-flex justify-between pe-4 ps-4 pt-4">
                            <h2 class="text-2xl font-bold text-gray-800">{{ institute.acronym }}</h2>
                            <div class="hs-dropdown relative inline-flex [--placement:bottom-left]">
                                <button id="hs-split-dropdown"
                                        type="button"
                                        class="hs-dropdown-toggle relative -ms-[.3125rem] inline-flex items-center gap-x-2 text-sm font-semibold rounded-e-md">
                                    <svg class="flex-none size-4 text-gray-600"
                                         xmlns="http://www.w3.org/2000/svg"
                                         width="24"
                                         height="24"
                                         viewBox="0 0 24 24"
                                         fill="none"
                                         stroke="currentColor"
                                         stroke-width="2"
                                         stroke-linecap="round"
                                         stroke-linejoin="round">
                                        <circle cx="12" cy="12" r="1" /><circle cx="12" cy="5" r="1" /><circle cx="12" cy="19" r="1" />
                                    </svg>
                                </button>
                                <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden divide-y divide-gray-200 min-w-40 z-20 bg-white shadow-2xl rounded-lg p-2 mt-2"
                                     aria-labelledby="hs-table-dropdown-1">
                                    <div class="py-2 first:pt-0 last:pb-0">
                                        <span class="block py-2 px-3 text-xs font-medium uppercase text-gray-400">Actions</span>
                                        <a class="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500"
                                           href="#">View</a>
                                        <button data-hs-overlay="#edit-institute"
                                                type="button"
                                                class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                            Edit
                                        </button>
                                    </div>
                                    <div class="py-2 first:pt-0 last:pb-0">
                                        <button data-hs-overlay="#delete-institute"
                                                type="button"
                                                class="w-full flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-red-600 hover:bg-gray-100 focus:ring-2 focus:ring-primary-500">
                                            Delete
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pe-4 ps-4">
                            <p class="mt-2 text-gray-500">{{ institute.institute_name }}</p>
                        </div>
                        <div class="pb-4 pe-4 ps-4 mt-auto">
                            <a class=" mt-3  inline-flex items-center gap-x-1 text-sm font-semibold rounded-lg border border-transparent text-primary-600 hover:primary-blue-800 disabled:opacity-50 disabled:pointer-events-none"
                               href="{% url 'institutes:assign-faculty' %}">
                                View institute
                                <svg class="flex-shrink-0 size-4"
                                     xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24"
                                     viewBox="0 0 24 24"
                                     fill="none"
                                     stroke="currentColor"
                                     stroke-width="2"
                                     stroke-linecap="round"
                                     stroke-linejoin="round">
                                    <path d="m9 18 6-6-6-6"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}